// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gdpevaegurnpnjgqrchn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdkcGV2YWVndXJucG5qZ3FyY2huIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg4ODYwMDEsImV4cCI6MjA3NDQ2MjAwMX0.owOdTJRhIG5C2guxH1-3Eo4aM04lAsm9yvXSY52ob0M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});